spring:
  application:
    name: LibraryService
  datasource:
    url: jdbc:postgresql://localhost:5430/libraryService
    username: postgres
    password: "1234"
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 8081